swagger: '2.0'
info:
  description: API do microserviço que gerencia `salas`
  version: 1.0.0
  title: API salas
host: 'http://ec2-3-128-87-176.us-east-2.compute.amazonaws.com:3001/docs/'
basePath: /
tags:
  - name: rooms
    description: Manipulação de salas
schemes:
  - http
paths:
  /room:
    get:
      tags:
        - salas
      summary: Lista todos as salas
      operationId: getSalas
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Rooms'
        '404':
          description: 'Not Found: Objetos não encontrados'
          schema:
            $ref: '#/definitions/Rooms'
    post:
      tags:
        - salas
      summary: Cria uma sala
      operationId: postSala
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Room'
      consumes: 
      - application/json
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Rooms'
        '500':
          description: 'Internal Server Error'
  '/room/{id}':
    get:
      tags:
        - salas
      summary: Lista uma sala pelo seu id
      operationId: getSala
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Rooms'
        '404':
        description: 'Not Found: Objeto não encontrado'
          schema:
            $ref: '#/definitions/Rooms'
    put:
      tags:
        - salas
      summary: Atualiza uma sala pelo seu id
      operationId: putSala
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Room'
      responses:
        '200':
          description: Ok
        '404':
          description: 'Not found: Objeto não encontrado'
    patch:
      tags:
        - salas
      summary: Atualiza parcialmente uma sala pelo seu id
      operationId: patchSala
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Room'
      responses:
        '200':
          description: Ok
        '404':
          description: 'Not found: Objeto não encontrado'
        '400':
          description: 'Bad Request'
    delete:
      tags:
        - salas
      summary: Deleta uma Sala pelo seu id
      operationId: deleteSala
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: 'Ok'
        '404':
          description: 'Not Found: Objeto não encontrado'
definitions:
  Rooms:
    type: array
    items:
      $ref: '#/definitions/Room'
  Room:
    type: object
    required:
      - number
      - towerNumber
      - capacity
      - resources
      - online
      - url
    properties:
      number:
        type: number
      towerNumber:
        type: number
      capacity:
        type: number
      resources:
        type: array
        items:
          type: string
      online:
        items:
          type: boolean
      url:
        type: string
    example:
      number: '250'
      towerNumber: '32'
      capacity: 90
      resources:
        - nada
      online: false
      url: 'http://www.zoom.com/ehosguri'
      turmas: 
        - '5f9375c46c782394b6e84cc0'
      aulas:
        - '5f8e0e68dd385b00119407fa'
        - '5f91fca7dd385b00119407fb'

